[2022-08-04 17:35:04,533] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: btc_price_operator.send_price_email manual__2022-08-04T17:35:00.049854+00:00 [queued]>
[2022-08-04 17:35:04,552] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: btc_price_operator.send_price_email manual__2022-08-04T17:35:00.049854+00:00 [queued]>
[2022-08-04 17:35:04,552] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2022-08-04 17:35:04,552] {taskinstance.py:1242} INFO - Starting attempt 1 of 1
[2022-08-04 17:35:04,552] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-08-04 17:35:04,578] {taskinstance.py:1262} INFO - Executing <Task(EmailOperator): send_price_email> on 2022-08-04 17:35:00.049854+00:00
[2022-08-04 17:35:04,584] {standard_task_runner.py:52} INFO - Started process 142 to run task
[2022-08-04 17:35:04,591] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'btc_price_operator', 'send_price_email', 'manual__2022-08-04T17:35:00.049854+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/btc_price.py', '--cfg-path', '/tmp/tmpsw0_4_xs', '--error-file', '/tmp/tmpeuqioexz']
[2022-08-04 17:35:04,592] {standard_task_runner.py:77} INFO - Job 6: Subtask send_price_email
[2022-08-04 17:35:04,661] {logging_mixin.py:109} INFO - Running <TaskInstance: btc_price_operator.send_price_email manual__2022-08-04T17:35:00.049854+00:00 [running]> on host 81472222a2e9
[2022-08-04 17:35:04,841] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=btc_price_operator
AIRFLOW_CTX_TASK_ID=send_price_email
AIRFLOW_CTX_EXECUTION_DATE=2022-08-04T17:35:00.049854+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-08-04T17:35:00.049854+00:00
[2022-08-04 17:35:04,861] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/email.py:102: PendingDeprecationWarning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
  send_mime_email(e_from=smtp_mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)

[2022-08-04 17:35:04,862] {configuration.py:381} WARNING - section/key [smtp/smtp_user] not found in config
[2022-08-04 17:35:04,862] {email.py:208} INFO - Email alerting: attempt 1
[2022-08-04 17:35:04,863] {taskinstance.py:1703} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1332, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1458, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1514, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/email.py", line 88, in execute
    conn_id=self.conn_id,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 66, in send_email
    **kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 102, in send_email_smtp
    send_mime_email(e_from=smtp_mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 210, in send_mime_email
    conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 244, in _get_smtp_connection
    else smtplib.SMTP(host=host, port=port, timeout=timeout)
  File "/usr/local/lib/python3.7/smtplib.py", line 251, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/local/lib/python3.7/smtplib.py", line 336, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/local/lib/python3.7/smtplib.py", line 307, in _get_socket
    self.source_address)
  File "/usr/local/lib/python3.7/socket.py", line 728, in create_connection
    raise err
  File "/usr/local/lib/python3.7/socket.py", line 716, in create_connection
    sock.connect(sa)
OSError: [Errno 99] Cannot assign requested address
[2022-08-04 17:35:04,885] {taskinstance.py:1280} INFO - Marking task as FAILED. dag_id=btc_price_operator, task_id=send_price_email, execution_date=20220804T173500, start_date=20220804T173504, end_date=20220804T173504
[2022-08-04 17:35:04,913] {standard_task_runner.py:91} ERROR - Failed to execute job 6 for task send_price_email
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 292, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1332, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1458, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1514, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/email.py", line 88, in execute
    conn_id=self.conn_id,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 66, in send_email
    **kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 102, in send_email_smtp
    send_mime_email(e_from=smtp_mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 210, in send_mime_email
    conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 244, in _get_smtp_connection
    else smtplib.SMTP(host=host, port=port, timeout=timeout)
  File "/usr/local/lib/python3.7/smtplib.py", line 251, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/local/lib/python3.7/smtplib.py", line 336, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/local/lib/python3.7/smtplib.py", line 307, in _get_socket
    self.source_address)
  File "/usr/local/lib/python3.7/socket.py", line 728, in create_connection
    raise err
  File "/usr/local/lib/python3.7/socket.py", line 716, in create_connection
    sock.connect(sa)
OSError: [Errno 99] Cannot assign requested address
[2022-08-04 17:35:04,963] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-08-04 17:35:05,077] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
